vich_uploader:
    db_driver: orm

    mappings:
       pdf:
           uri_prefix: /files/pdf
           upload_destination: '%kernel.project_dir%/public/files/pdf'
           namer: Vich\UploaderBundle\Naming\UniqidNamer

           inject_on_load: false
           delete_on_update: true
           delete_on_remove: true
        
       musicien_image:
           uri_prefix: /images/musiciens
           upload_destination: '%kernel.project_dir%/public/images/musiciens'
           namer: Vich\UploaderBundle\Naming\UniqidNamer

           inject_on_load: false
           delete_on_update: true
           delete_on_remove: true
        
       article_image:
           uri_prefix: /images/articles
           upload_destination: '%kernel.project_dir%/public/images/articles'
           namer: Vich\UploaderBundle\Naming\UniqidNamer

           inject_on_load: false
           delete_on_update: true
           delete_on_remove: true
        
       instrument_image:
           uri_prefix: /images/instruments
           upload_destination: '%kernel.project_dir%/public/images/instruments'
           namer: Vich\UploaderBundle\Naming\UniqidNamer

           inject_on_load: false
           delete_on_update: true
           delete_on_remove: true

